"""THE canonical interactive drawing protocol. One implementation, four callers.

The 0.115 drawing-history gap was produced by a specific experiment:
``strokes_from_raster`` decomposing a PADDED 56x56 raster into row segments,
``drawing.replay`` evolving the CA between strokes at ``steps_between=4``, and a
matched post-completion rollout. Its number is **image-level final majority-vote
digit accuracy**: complete 0.445 versus progressive 0.330.

A later preflight measured something else -- per-cell accuracy on a half-hidden
28x28 image -- and got 0.0068. Different protocol, different unit, so it could
not test the 0.08 threshold the frozen value implies. The threshold was right;
the measurement was not.

So the protocol lives here once. ``experiments/mnist_interactive.py``, the
Phase C2 preflight, the Phase C2 trainer and the Phase C2 evaluator all call
``run_arms``; none reimplements it. The regression test
``test_shared_protocol_matches_the_original_evaluator`` pins this module's
output to the original evaluator's on identical records, schedules and
checkpoint.

Primary metric: **image-level digit accuracy** (``digit_accuracy``), the
majority vote over living cells at the final step. Cell accuracy is reported as
secondary. Mixing the two is what produced the invalid preflight, and
``target1_primary_metric`` exists so callers name the unit explicitly.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import torch

from .drawing import (
    DEFAULT_RADIUS, GRID, DrawingRecord, Stroke, apply_stroke, blank_state,
    pad_mnist, rasterise_segment, render, reset_mutable,
)
from .stochastic import reference_identical_schedule, schedule_for_ids

# Frozen: these are the settings that produced the 0.115 baseline.
STEPS_BETWEEN = 4
POST_STEPS = 200
RADIUS = DEFAULT_RADIUS
ARMS = ("complete", "progressive", "progressive_reset", "paused")
PRIMARY_METRIC = "digit_accuracy"        # image-level majority vote
SECONDARY_METRICS = ("cell_accuracy", "agreement", "confidently_wrong")


def target1_primary_metric() -> str:
    """The unit Target 1 is scored in. Callers must not substitute another."""
    return PRIMARY_METRIC


def strokes_from_raster(raster: np.ndarray, *, steps_between: int = STEPS_BETWEEN,
                        radius: float = RADIUS) -> DrawingRecord:
    """Decompose a raster into row-segment strokes. Procedural, not human.

    Identical to the original in ``experiments/mnist_interactive.py``; that
    module now imports this one so the two cannot drift.
    """
    grid = raster.shape[0]
    ys, xs = np.nonzero(raster > 0.1)
    rec = DrawingRecord(
        grid=grid, provenance="procedural-diagnostic",
        notes=(
            "Generated by decomposing an existing raster into row segments. "
            "NOT a human drawing. Stroke order and timing are synthetic."
        ),
    )
    if ys.size == 0:
        return rec
    t = 0.0
    for r in sorted(set(ys.tolist())):
        cols = np.sort(xs[ys == r])
        start = prev = cols[0]
        for c in list(cols[1:]) + [None]:
            if c is not None and c == prev + 1:
                prev = c
                continue
            rec.strokes.append(Stroke(
                t_ms=t, x0=float(start), y0=float(r), x1=float(prev),
                y1=float(r), radius=radius, erase=False,
                steps_after=steps_between,
            ))
            t += 16.0
            if c is None:
                break
            start = prev = c
    return rec


@dataclass
class ArmResult:
    arm: str
    digit_accuracy: float          # PRIMARY: image-level majority vote
    cell_accuracy: float           # secondary
    agreement: float
    confidently_wrong: float
    pre_completion_updates: int
    post_completion_updates: int
    per_image_correct: np.ndarray
    per_image_cell: np.ndarray

    def summary(self) -> dict:
        return {
            "arm": self.arm,
            "digit_accuracy": self.digit_accuracy,
            "cell_accuracy": self.cell_accuracy,
            "agreement": self.agreement,
            "confidently_wrong": self.confidently_wrong,
            "pre_completion_updates": self.pre_completion_updates,
            "post_completion_updates": self.post_completion_updates,
            "n_images": int(self.per_image_correct.size),
            "primary_metric": PRIMARY_METRIC,
        }


@torch.no_grad()
def run_arms(model, images, labels, example_ids, *, arms=ARMS,
             steps_between: int = STEPS_BETWEEN, post_steps: int = POST_STEPS,
             eval_seed: int = 20260911, device=None,
             radius: float = RADIUS) -> dict[str, ArmResult]:
    """Run the canonical drawing arms on padded 56x56 procedural drawings.

    ``images`` are 28x28 MNIST images; each is PADDED into the 56x56 grid, the
    way the demo places a sample, and decomposed into strokes. Every arm shares
    one post-completion schedule keyed on the example ids, so arms differ only
    by what history survives.
    """
    device = device or next(model.parameters()).device
    imgs = images.detach().cpu().numpy() if torch.is_tensor(images) else images
    labs = labels.to(device) if torch.is_tensor(labels) else torch.as_tensor(
        labels, device=device)
    ch = model.channel_n + 1
    n = len(imgs)

    out: dict[str, ArmResult] = {}
    acc = {a: {"correct": [], "cell": [], "agree": [], "cw": [], "pre": 0}
           for a in arms}

    for i in range(n):
        raster = pad_mnist(imgs[i])
        rec = strokes_from_raster(raster, steps_between=steps_between,
                                  radius=radius)
        total_live = sum(s.steps_after for s in rec.strokes)
        sched = reference_identical_schedule(
            [int(example_ids[i])], steps=post_steps, total_channels=model.channel_n,
            fire_rate=model.config.fire_rate, eval_seed=eval_seed,
            stage="draw-post", add_noise=model.config.add_noise,
            noise_std=model.config.noise_std, height=GRID, width=GRID,
            device=device,
        )
        live = None
        if total_live:
            live = reference_identical_schedule(
                [int(example_ids[i])], steps=total_live,
                total_channels=model.channel_n, fire_rate=model.config.fire_rate,
                eval_seed=eval_seed, stage="draw-live",
                add_noise=model.config.add_noise,
                noise_std=model.config.noise_std, height=GRID, width=GRID,
                device=device,
            )

        for arm in arms:
            draws_live = arm in ("progressive", "progressive_reset")
            pre = 0
            if arm == "complete":
                s = blank_state(ch, GRID, device)
                s[0, 0] = torch.as_tensor(render(rec), device=device,
                                          dtype=s.dtype)
            else:
                s = blank_state(ch, GRID, device)
                cursor = 0
                for st in rec.strokes:
                    a = rasterise_segment(GRID, st.x0, st.y0, st.x1, st.y1,
                                          st.radius)
                    s = apply_stroke(s, a, erase=st.erase)
                    if draws_live:
                        for _ in range(st.steps_after):
                            s = model(s, fire=live.fire[cursor],
                                      noise=None if live.noise is None
                                      else live.noise[cursor])
                            cursor += 1
                            pre += 1
                if arm == "progressive_reset":
                    s = reset_mutable(s)

            alive = model.living_mask(s)
            for t in range(post_steps):
                s = model(s, fire=sched.fire[t],
                          noise=None if sched.noise is None else sched.noise[t])

            logits = model.classify(s)
            a2 = alive[:, 0]
            na = a2.flatten(1).sum(1).clamp(min=1)
            cp = logits.argmax(1)
            votes = torch.zeros(1, logits.shape[1], device=device)
            for c in range(logits.shape[1]):
                votes[:, c] = ((cp == c) & a2).flatten(1).sum(1).to(votes.dtype)
            pred = int(votes.argmax(1))
            top = float(votes.max(1).values)
            agree = top / float(na)
            correct = pred == int(labs[i])
            cell = float(((cp == labs[i]) & a2).flatten(1).sum(1)) / float(na)

            acc[arm]["correct"].append(float(correct))
            acc[arm]["cell"].append(cell)
            acc[arm]["agree"].append(agree)
            acc[arm]["cw"].append(float((not correct) and agree >= 0.95))
            acc[arm]["pre"] = pre

    for arm in arms:
        a = acc[arm]
        out[arm] = ArmResult(
            arm=arm,
            digit_accuracy=float(np.mean(a["correct"])),
            cell_accuracy=float(np.mean(a["cell"])),
            agreement=float(np.mean(a["agree"])),
            confidently_wrong=float(np.mean(a["cw"])),
            pre_completion_updates=a["pre"],
            post_completion_updates=post_steps,
            per_image_correct=np.array(a["correct"]),
            per_image_cell=np.array(a["cell"]),
        )
    return out


def history_gap(results: dict[str, ArmResult]) -> dict:
    """The Target 1 baseline effect, in the unit the frozen value uses.

    ``progressive_reset`` must reproduce ``complete``: it performs the same
    strokes and the same pre-completion updates, then clears the learned state.
    If it matches, the loss is attributable to RETAINED HISTORY rather than to
    the extra computation the progressive arm also does.
    """
    comp = results["complete"]
    prog = results["progressive"]
    reset = results.get("progressive_reset")
    gap = comp.digit_accuracy - prog.digit_accuracy
    out = {
        "metric": PRIMARY_METRIC,
        "complete_digit_accuracy": comp.digit_accuracy,
        "progressive_digit_accuracy": prog.digit_accuracy,
        "history_gap": gap,
        "complete_cell_accuracy": comp.cell_accuracy,
        "progressive_cell_accuracy": prog.cell_accuracy,
        "cell_level_gap_secondary": comp.cell_accuracy - prog.cell_accuracy,
        "progressive_extra_updates": prog.pre_completion_updates,
    }
    if reset is not None:
        out.update({
            "progressive_reset_digit_accuracy": reset.digit_accuracy,
            "reset_reproduces_complete": bool(
                abs(reset.digit_accuracy - comp.digit_accuracy) <= 1e-9),
            "reset_extra_updates": reset.pre_completion_updates,
            "attribution": (
                "progressive_reset performs the same strokes and the same "
                "pre-completion updates as progressive, then clears the "
                "learned state. Matching complete attributes the loss to "
                "retained history, not to extra computation."
            ),
        })
    return out


# --------------------------------------------------------------------------
# The one frozen protocol.
#
# Training, evaluation and the conditional stage all load the SAME file and
# read their numbers from it. Importing thresholds from Python while a
# separate JSON claimed to be "the freeze" let the two drift apart, so this
# validator refuses a protocol that cannot drive the whole run.
# --------------------------------------------------------------------------

PROTOCOL_REQUIRED = (
    "primary_endpoints", "preregistered_effects", "protocols", "datasets",
    "reference_checkpoint", "substrate_gate", "variants", "training",
)


class InvalidProtocol(RuntimeError):
    """The frozen protocol is missing, malformed, or does not match the run."""


def load_protocol(path, *, reference=None, require_endpoints=()):
    """Load and validate the frozen protocol.

    ``reference`` (a checkpoint path) is hashed and compared against the
    protocol, so a run cannot silently substitute a different substrate for
    the one the thresholds were frozen against.
    """
    import hashlib
    import json
    from pathlib import Path

    p = Path(path)
    if not p.exists():
        raise InvalidProtocol(
            f"no frozen protocol at {p}. Nothing may be trained or scored "
            "without it -- run experiments/mnist_decisive_freeze.py first."
        )
    try:
        fz = json.loads(p.read_text())
    except json.JSONDecodeError as exc:
        raise InvalidProtocol(f"{p} is not valid JSON: {exc}") from exc

    missing = [k for k in PROTOCOL_REQUIRED if k not in fz]
    if missing:
        raise InvalidProtocol(
            f"{p} is missing {missing}. This is not the decisive protocol; "
            "an older or partial freeze cannot drive training and evaluation."
        )
    for ep in require_endpoints:
        if ep not in fz["primary_endpoints"]:
            raise InvalidProtocol(
                f"{p} declares no endpoint {ep!r}; refusing to score it."
            )
        if "criteria" not in fz["primary_endpoints"][ep]:
            raise InvalidProtocol(f"{p}: endpoint {ep!r} declares no criteria")

    if reference is not None:
        h = hashlib.sha256()
        with Path(reference).open("rb") as fh:
            for c in iter(lambda: fh.read(1 << 20), b""):
                h.update(c)
        got, want = h.hexdigest(), fz["reference_checkpoint"]["sha256"]
        if got != want:
            raise InvalidProtocol(
                f"substrate mismatch: {reference} hashes to {got[:16]} but "
                f"the protocol was frozen against {want[:16]}. The frozen "
                "thresholds do not describe this checkpoint."
            )
    return fz


def preregistered(fz, name):
    """Read a preregistered effect from the protocol, never recomputed."""
    eff = fz["preregistered_effects"]
    if name not in eff:
        raise InvalidProtocol(
            f"the protocol declares no preregistered {name!r}; refusing to "
            "substitute a value measured from the loaded model."
        )
    return float(eff[name])
