"""The learned multi-hop memory under redelivery, every arm, content readout.

Reads the per-seed outputs of experiments/musique_duplication_eval.py for the
two-hop sweep and reports top-1 accuracy, negative log-likelihood and mean
reciprocal rank from the content readout. That readout scores candidates by
similarity alone, so it does not depend on the credit coefficient, whose split
from the intercept the calibration cannot identify. Every arm is included,
the provenance-free control among them.

Exact redelivery is the main comparison. Re-chunking is reported in the
appendix. The frozen sweep used `partial_windows`, which yields at most three
partial windows and never the full paragraph, so the ledger could only keep a
partial window there and the provenance-free control led. When the `rechunk`
sweep of scripts/dgx_rechunk.sh is present, which delivers the paragraph in
full and then distinct windows cut from it, its table and macros are written
too, together with the sentinel \\RechunkArmReady that switches the manuscript
to it. The frozen sweep's macros are always written, because the appendix
still reports the earlier construction.
"""
from __future__ import annotations

import glob
import json
import math
import os
import statistics as st
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "paper" / "generated"
SRC = ROOT / "results" / "musique_dup_iclr_fusion_h2" / "eval"
RECHUNK = ROOT / "results" / "musique_rechunk_h2" / "eval"
FRAGMENTS = ROOT / "results" / "musique_fragments_h2" / "eval"
DETECTOR_NAME = {"canonical_dedup": "canonical hashing", "minhash_dedup": "MinHash",
                 "simhash_dedup": "SimHash", "embed_dedup": "embedding detection"}
T975_4 = 2.776
ARMS = (("full", r"\textbf{Lineage ledger (this work)}"),
        ("canonical_dedup", r"Canonical hashing \citep{lee2022deduplicating}"),
        ("minhash_dedup", r"MinHash \citep{broder1997resemblance}"),
        ("simhash_dedup", r"SimHash \citep{charikar2002simhash}"),
        ("embed_dedup", r"Embedding detection \citep{xiao2023bge}"),
        ("plain", "No defence"))


def load(src=SRC):
    t = defaultdict(dict)
    for f in glob.glob(str(src / "*_s*.json")):
        d = json.loads(Path(f).read_text())
        for r in d["rows"]:
            if r["multiplicity"] == 1:
                # The clean stream, identical under every intervention.
                t[(d["variant"], "clean", 1)][d["seed"]] = r["content"]
            elif r["scope"] == "all_hops":
                t[(d["variant"], r["intervention"],
                   r["multiplicity"])][d["seed"]] = r["content"]
    return t


def load_accounting(src, iv, mult=16):
    """Credit over the ceiling and arrivals reaching the content path per
    record, all hops, at one multiplicity, averaged over seeds."""
    credit, reach = defaultdict(list), defaultdict(list)
    for f in glob.glob(str(src / "*_s*.json")):
        d = json.loads(Path(f).read_text())
        for r in d["rows"]:
            if (r["intervention"], r["scope"], r["multiplicity"]) == \
                    (iv, "all_hops", mult):
                credit[d["variant"]].append(r["credited_over_ceiling"])
                reach[d["variant"]].append(
                    (r["n_events"] - r["n_suppressed"]) / d["n_dev"])
                reach[(d["variant"], "events")].append(r["n_events"] / d["n_dev"])
    return ({k: st.mean(v) for k, v in credit.items()},
            {k: st.mean(v) for k, v in reach.items()})


def mean(t, arm, iv, m, key):
    return st.mean(v[key] for v in t[(arm, iv, m)].values())


def paired(t, a, b, iv, m, key):
    seeds = sorted(set(t[(a, iv, m)]) & set(t[(b, iv, m)]))
    d = [t[(a, iv, m)][s][key] - t[(b, iv, m)][s][key] for s in seeds]
    mu = st.mean(d)
    h = T975_4 * st.stdev(d) / math.sqrt(len(d))
    return mu, mu - h, mu + h


def body(t, iv):
    lines = ["% generated by analysis/learned_memory_table.py"]
    for arm, label in ARMS:
        cells = [f"${mean(t, arm, 'clean', 1, 'accuracy'):.4f}$"]
        cells += [f"${mean(t, arm, iv, m, 'accuracy'):.4f}$" for m in (4, 16)]
        cells += [f"${mean(t, arm, iv, 16, 'nll'):.4f}$",
                  f"${mean(t, arm, iv, 16, 'mrr'):.4f}$"]
        lines.append(" & ".join([label] + cells) + r" \\")
    body = "\n".join(lines).rstrip()
    return body[:-2].rstrip() + "\n" if body.endswith("\\\\") else body + "\n"


def main():
    os.chdir(ROOT)
    t = load()
    (GEN / "tab_learned_exact.tex").write_text(body(t, "exact"))
    (GEN / "tab_learned_overlap.tex").write_text(body(t, "overlap"))
    mac = {}
    for key, name in (("accuracy", "Acc"), ("nll", "Nll"), ("mrr", "Mrr")):
        mu, lo, hi = paired(t, "full", "plain", "exact", 16, key)
        mac[f"LmExact{name}Gain"] = f"{mu:+.4f}"
        mac[f"LmExact{name}GainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
    mac["LmLedgerExactSixteen"] = f"{mean(t, 'full', 'exact', 16, 'accuracy'):.4f}"
    mac["LmPlainExactSixteen"] = f"{mean(t, 'plain', 'exact', 16, 'accuracy'):.4f}"
    mac["LmLedgerClean"] = f"{mean(t, 'full', 'clean', 1, 'accuracy'):.4f}"
    mac["LmPlainOverlapFour"] = f"{mean(t, 'plain', 'overlap', 4, 'accuracy'):.4f}"
    mac["LmLedgerOverlapFour"] = f"{mean(t, 'full', 'overlap', 4, 'accuracy'):.4f}"
    mac["LmDedupOverlapFour"] = f"{mean(t, 'canonical_dedup', 'overlap', 4, 'accuracy'):.4f}"
    mac["LmPlainOverlapSixteen"] = f"{mean(t, 'plain', 'overlap', 16, 'accuracy'):.4f}"
    mu, lo, hi = paired(t, "full", "plain", "overlap", 16, "accuracy")
    mac["LmOverlapAccGain"] = f"{mu:+.4f}"
    mac["LmOverlapAccGainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
    mac["LmLedgerOverlapSixteen"] = f"{mean(t, 'full', 'overlap', 16, 'accuracy'):.4f}"
    r = load(RECHUNK)
    arms = {a for a, _ in ARMS}
    have = {k[0] for k in r if k[1] == "rechunk" and k[2] == 16}
    if arms <= have:
        (GEN / "tab_learned_rechunk.tex").write_text(body(r, "rechunk"))
        for key, name in (("accuracy", "Acc"), ("nll", "Nll"), ("mrr", "Mrr")):
            mu, lo, hi = paired(r, "full", "plain", "rechunk", 16, key)
            mac[f"LmRechunk{name}Gain"] = f"{mu:+.4f}"
            mac[f"LmRechunk{name}GainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
        # The strongest surface detector at sixteenfold, by accuracy.
        best = max((a for a, _ in ARMS if a not in ("full", "plain")),
                   key=lambda a: mean(r, a, "rechunk", 16, "accuracy"))
        mu, lo, hi = paired(r, "full", best, "rechunk", 16, "accuracy")
        mac["LmRechunkBestDetector"] = DETECTOR_NAME[best]
        mac["LmRechunkDetGain"] = f"{mu:+.4f}"
        mac["LmRechunkDetGainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
        mac["LmRechunkLedgerSixteen"] = f"{mean(r, 'full', 'rechunk', 16, 'accuracy'):.4f}"
        mac["LmRechunkPlainSixteen"] = f"{mean(r, 'plain', 'rechunk', 16, 'accuracy'):.4f}"
        mac["LmRechunkLedgerClean"] = f"{mean(r, 'full', 'clean', 1, 'accuracy'):.4f}"
        mac["RechunkArmReady"] = "1"
    else:
        stale = GEN / "tab_learned_rechunk.tex"
        if stale.exists():
            stale.unlink()
    f = load(FRAGMENTS)
    have = {k[0] for k in f if k[1] == "fragments" and k[2] == 16}
    if arms <= have and "RechunkArmReady" in mac:
        (GEN / "tab_learned_fragments.tex").write_text(body(f, "fragments"))
        for key, name in (("accuracy", "Acc"), ("nll", "Nll"), ("mrr", "Mrr")):
            mu, lo, hi = paired(f, "full", "plain", "fragments", 16, key)
            mac[f"LmFrag{name}Gain"] = f"{mu:+.4f}"
            mac[f"LmFrag{name}GainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
        # The registered comparison is against no defence. Against the
        # detectors, report the one with the highest accuracy.
        best = max((a for a, _ in ARMS if a not in ("full", "plain")),
                   key=lambda a: mean(f, a, "fragments", 16, "accuracy"))
        mu, lo, hi = paired(f, "full", best, "fragments", 16, "accuracy")
        mac["LmFragBestDetector"] = DETECTOR_NAME[best]
        mac["LmFragDetGain"] = f"{mu:+.4f}"
        mac["LmFragDetGainCI"] = f"[{lo:+.4f}, {hi:+.4f}]"
        credit, reach = load_accounting(FRAGMENTS, "fragments")
        mac["LmFragLedgerReach"] = f"{reach['full']:.1f}"
        mac["LmFragArrivals"] = f"{reach[('full', 'events')]:.0f}"
        mac["LmFragLedgerCredit"] = f"{credit['full']:.3f}"
        mac["LmFragPlainCredit"] = f"{credit['plain']:.3f}"
        # Main-text table: accuracy at sixteenfold in every regime, and the
        # credit each rule assigns when only fragments arrive.
        lines = ["% generated by analysis/learned_memory_table.py"]
        for arm, label in ARMS:
            cells = [f"${mean(t, arm, 'clean', 1, 'accuracy'):.4f}$",
                     f"${mean(t, arm, 'exact', 16, 'accuracy'):.4f}$",
                     f"${mean(r, arm, 'rechunk', 16, 'accuracy'):.4f}$",
                     f"${mean(f, arm, 'fragments', 16, 'accuracy'):.4f}$",
                     f"${credit[arm]:.3f}$"]
            lines.append(" & ".join([label] + cells) + r" \\")
        text = "\n".join(lines).rstrip()
        (GEN / "tab_learned_main.tex").write_text(text[:-2].rstrip() + "\n")
        mac["FragmentsArmReady"] = "1"
    lines = ["% generated by analysis/learned_memory_table.py"]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(mac.items())]
    (GEN / "learned_macros.tex").write_text("\n".join(lines) + "\n")
    for k, v in sorted(mac.items()):
        print(f"{k:>24} {v}")


if __name__ == "__main__":
    main()
