"""Tables and the figure for the syndication experiment and the source contest.

Every number in the generated files is read from a committed raw output:
results/musique_syndication/verdict.json, written by
analysis/syndication_analysis.py from the per-record reader outputs, and
results/gate1/contest.csv, written by experiments/gate1_mechanism.py. Nothing
is transcribed by hand, so rerunning this script after rerunning either
experiment regenerates the manuscript's numbers.
"""
from __future__ import annotations

import csv
import json
import os
import statistics as st
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "paper" / "generated"
FIG = ROOT / "paper" / "figures"

SYND_ARMS = (
    ("full", r"\textbf{Lineage ledger (this work)}", "Lineage ledger"),
    ("canonical_dedup", r"Canonical hashing \citep{lee2022deduplicating}",
     "Canonical hashing"),
    ("minhash_dedup", r"MinHash \citep{broder1997resemblance}", "MinHash"),
    ("simhash_dedup",
     r"SimHash \citep{charikar2002simhash, manku2007nearduplicate}",
     "SimHash"),
    ("plain", "No defence", "No defence"),
)

CONTEST = (
    ("ec_exact", r"\textbf{Lineage ledger (this work)}"),
    ("cov_int", r"Covariance intersection \citep{julier1997ci}"),
    ("inv_cov_int", r"Inverse covariance intersection \citep{noack2017ici}"),
    ("mean_pool", r"Mean pooling \citep{zaheer2017deepsets}"),
    ("bp_cavity", r"Gaussian belief propagation \citep{weiss2001gaussianbp}"),
    ("bp_backtrack", r"Loopy propagation with backtracking \citep{murphy1999loopy}"),
    ("bp_trw", r"Tree-reweighted propagation \citep{wainwright2003trw}"),
    ("naive_sum", "Summation of every arrival"),
)


def write_body(path, lines):
    """Write a table body whose final row break the manuscript supplies.

    A row break at the very end of an \\input file is followed by the end of
    the file, and a rule after it then raises a misplaced \\noalign error.
    """
    body = "\n".join(lines).rstrip()
    if body.endswith("\\\\"):
        body = body[:-2].rstrip()
    path.write_text(body + "\n")


def f4(x):
    return f"${x:.4f}$"


def syndication(verdict):
    d = verdict["dose_response"]

    def cell(pos, arm, style, m, key):
        return d[f"{pos}/{arm}/{style}/{m}"][key]

    rows = []
    worst = {}
    for arm, _, _ in SYND_ARMS:
        vals = [cell("last", arm, "exact", 16, "gold_recall"),
                cell("last", arm, "exact", 16, "misled"),
                cell("last", arm, "boilerplate", 16, "gold_recall"),
                cell("last", arm, "boilerplate", 16, "misled"),
                cell("first", arm, "exact", 1, "gold_recall"),
                cell("first", arm, "exact", 1, "true_final_in_context")]
        worst[arm] = min(vals[0], vals[2], vals[4])
        rows.append((arm, vals, cell("last", arm, "exact", 16,
                                     "n_context_tokens")))
    best_worst = max(worst.values())
    lines = ["% generated by analysis/story_tables.py"]
    for (arm, label, _), (_, vals, tokens) in zip(SYND_ARMS, rows):
        w = f4(worst[arm])
        if worst[arm] == best_worst:
            w = r"$\mathbf{" + f"{worst[arm]:.4f}" + "}$"
        lines.append(" & ".join([label] + [f4(v) for v in vals]
                                + [w, f"${tokens:.1f}$"]) + r" \\")
    write_body(GEN / "tab_syndication.tex", lines)

    # macros for the numbers quoted in running text
    p = verdict["predictions"]
    c = verdict["contrasts"]

    def iv(x):
        return f"[{x['ci_low']:+.4f}, {x['ci_high']:+.4f}]"

    mac = {
        "SyndPlainOne": f"{cell('last', 'plain', 'exact', 1, 'gold_recall'):.4f}",
        "SyndPlainSixteen": f"{cell('last', 'plain', 'exact', 16, 'gold_recall'):.4f}",
        "SyndMisledOne": f"{cell('last', 'plain', 'exact', 1, 'misled'):.4f}",
        "SyndMisledSixteen": f"{cell('last', 'plain', 'exact', 16, 'misled'):.4f}",
        "SyndDrop": f"{p['P1']['diff']:+.4f}", "SyndDropCI": iv(p["P1"]),
        "SyndGain": f"{p['P2']['diff']:+.4f}", "SyndGainCI": iv(p["P2"]),
        "SyndMisledRise": f"{p['P3']['diff']:+.4f}",
        "SyndMisledRiseCI": iv(p["P3"]),
        "SyndMinhashFirst": f"{p['P5']['diff']:+.4f}",
        "SyndMinhashFirstCI": iv(p["P5"]),
        "SyndCanonPlain": f"{p['P4']['diff']:+.4f}",
        "SyndCanonPlainCI": iv(p["P4"]),
        "SyndHeld": str(sum(bool(x["holds"]) for x in p.values())),
        "SyndPredictions": str(len(p)),
    }
    for key, name in (("last/boilerplate/16/full-canonical_dedup/gold_recall",
                       "SyndCanonBoiler"),
                      ("last/boilerplate/16/full-canonical_dedup/misled",
                       "SyndCanonBoilerMisled"),
                      ("last/boilerplate/16/full-simhash_dedup/gold_recall",
                       "SyndSimBoiler"),
                      ("first/boilerplate/1/full-minhash_dedup/gold_recall",
                       "SyndMinhashFirstBoiler"),
                      ("last/exact/16/full-minhash_dedup/gold_recall",
                       "SyndMinhashLast"),
                      ("first/exact/16/full-plain/gold_recall",
                       "SyndFirstPlainGold"),
                      ("first/exact/16/full-plain/misled",
                       "SyndFirstPlainMisled")):
        mac[name] = f"{c[key]['diff']:+.4f}"
        mac[name + "CI"] = iv(c[key])
    ledger_tok = cell("last", "full", "exact", 16, "n_context_tokens")
    plain_tok = cell("last", "plain", "exact", 16, "n_context_tokens")
    mac["SyndLedgerTokens"] = f"{ledger_tok:.1f}"
    mac["SyndPlainTokens"] = f"{plain_tok:.1f}"
    mac["SyndTokenRatio"] = f"{plain_tok / ledger_tok:.1f}"
    mac["SyndMinhashTrueLost"] = (
        f"{100 * (1 - cell('first', 'minhash_dedup', 'exact', 1, 'true_final_in_context')):.0f}")
    mac["SyndMinhashTrueKept"] = (
        f"{cell('first', 'minhash_dedup', 'exact', 1, 'true_final_in_context'):.4f}")
    return mac


def syndication_full(verdict):
    """Every arm, style, order and multiplicity, for the appendix.

    One body per arrival order, because a \\multicolumn header cannot open an
    \\input file, so the headers live in the manuscript.
    """
    d = verdict["dose_response"]
    for pos in ("last", "first"):
        lines = ["% generated by analysis/story_tables.py"]
        for arm, label, _ in SYND_ARMS:
            for style, sname in (("exact", "verbatim"),
                                 ("boilerplate", "reworded")):
                ys = [d[f"{pos}/{arm}/{style}/{m}"]["gold_recall"]
                      for m in (1, 2, 4, 8, 16)]
                lines.append(f"{label} & {sname} & "
                             + " & ".join(f4(y) for y in ys) + r" \\")
        write_body(GEN / f"tab_syndication_full_{pos}.tex", lines)


def syndication_figure(verdict):
    d = verdict["dose_response"]
    mults = (1, 2, 4, 8, 16)
    sns.set_theme(style="whitegrid", context="paper")
    fig, axes = plt.subplots(1, 3, figsize=(7.4, 2.5),
                             gridspec_kw={"width_ratios": [1, 1, 0.9]})
    pal = sns.color_palette("deep", len(SYND_ARMS))
    for ax, style, title in ((axes[0], "exact", "Verbatim copies"),
                             (axes[1], "boilerplate", "Reworded copies")):
        # Several arms coincide exactly, so each gets its own marker and the
        # ledger is drawn on top rather than hidden beneath an equal curve.
        for (arm, _, name), col, mk in zip(SYND_ARMS, pal, "osD^v"):
            ys = [d[f"last/{arm}/{style}/{m}"]["gold_recall"] for m in mults]
            ax.plot(mults, ys, marker=mk, color=col, label=name,
                    markersize=6.5 if arm == "full" else 4.5,
                    linewidth=2.4 if arm == "full" else 1.3,
                    linestyle="-" if arm == "full" else "--",
                    zorder=5 if arm == "full" else 3)
        ax.set_xscale("log", base=2)
        ax.set_xticks(mults)
        ax.set_xticklabels([str(m) for m in mults])
        ax.set_xlabel("Copies of the false paragraph")
        ax.set_title(title)
        ax.set_ylim(0.2, 0.65)
    axes[0].set_ylabel("Gold answer recall")
    names = [n for _, _, n in SYND_ARMS]
    ys = [d[f"first/{arm}/exact/1"]["gold_recall"] for arm, _, _ in SYND_ARMS]
    axes[2].barh(range(len(names)), ys, color=pal)
    axes[2].set_yticks(range(len(names)))
    axes[2].set_yticklabels(names, fontsize=7)
    axes[2].invert_yaxis()
    axes[2].set_xlim(0.0, 0.65)
    axes[2].set_xlabel("Gold answer recall")
    axes[2].set_title("False paragraph first")
    axes[0].legend(fontsize=6.5, loc="lower left", frameon=True)
    fig.tight_layout()
    FIG.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG / "fig_syndication.pdf", bbox_inches="tight")
    plt.close(fig)


def contest():
    rows = defaultdict(list)
    with open(ROOT / "results" / "gate1" / "contest.csv") as fh:
        for r in csv.DictReader(fh):
            rows[r["method"]].append(r)
    lines = ["% generated by analysis/story_tables.py"]
    mac = {}
    for method, label in CONTEST:
        rs = rows[method]
        two = st.mean(float(r["conf_two_distinct"]) for r in rs)
        hun = st.mean(float(r["conf_hundred_copies"]) for r in rs)
        win = 100 * st.mean(int(r["two_wins"]) for r in rs)
        win_m = 100 * st.mean(int(r["two_wins_mass"]) for r in rs)
        lines.append(f"{label} & ${two:.2f}$ & ${hun:.2f}$ & "
                     f"${win:.0f}\\%$ & ${win_m:.0f}\\%$ \\\\")
        mac["Contest" + method.replace("_", "").title()] = f"{win:.0f}"
    mac["ContestSeeds"] = str(len(rows["ec_exact"]))
    write_body(GEN / "tab_contest.tex", lines)
    return mac


def reader_efficiency():
    """Context cost of benign redelivery for a frozen reader, one seed.

    The exact and overlap regimes carry no seeded randomness, so seed 0 is the
    whole experiment rather than a sample of it.
    """
    base = ROOT / "results" / "musique_reader" / "eval"
    mac = {}
    for arm, tag in (("full", "Ledger"), ("plain", "Plain"),
                     ("canonical_dedup", "Canon")):
        doc = json.loads((base / f"{arm}_s0.json").read_text())
        for r in doc["rows"]:
            if r["multiplicity"] != 16:
                continue
            key = "Exact" if r["intervention"] == "exact" else "Overlap"
            mac[f"Reader{tag}{key}Tokens"] = f"{r['n_context_tokens']:.1f}"
            mac[f"Reader{tag}{key}Recall"] = f"{r['answer_recall']:.4f}"
        mac["ReaderRecords"] = str(doc["n_records"])
    for key in ("Exact", "Overlap"):
        mac[f"Reader{key}Ratio"] = (
            f"{float(mac[f'ReaderPlain{key}Tokens']) / float(mac[f'ReaderLedger{key}Tokens']):.1f}")
    return mac


def main():
    os.chdir(ROOT)
    verdict = json.loads(
        (ROOT / "results" / "musique_syndication" / "verdict.json").read_text())
    mac = syndication(verdict)
    mac.update(contest())
    mac.update(reader_efficiency())
    syndication_figure(verdict)
    syndication_full(verdict)
    out = ["% generated by analysis/story_tables.py"]
    out += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(mac.items())]
    (GEN / "story_macros.tex").write_text("\n".join(out) + "\n")
    for k, v in sorted(mac.items()):
        print(f"{k:>28} {v}")


if __name__ == "__main__":
    main()
